version: '3.8'

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
      - "2221:22"
    volumes:
      - ./flask_app:/app  # Flask 애플리케이션 디렉토리 마운트
    command: ["/bin/sh", "-c", "/usr/sbin/sshd && python3 /app/blockAPI.py"]  # SSH 서버 및 Flask 애플리케이션 실행 명령어
    environment:
      - FLASK_ENV=development

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
      - "2222:22"
    volumes:
      - ./flask_app:/app  # Flask 애플리케이션 디렉토리 마운트
    command: ["/bin/sh", "-c", "/usr/sbin/sshd && python3 /app/blockAPI.py"]  # SSH 서버 및 Flask 애플리케이션 실행 명령어
    environment:
      - FLASK_ENV=development

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
      - "2223:22"
    volumes:
      - ./flask_app:/app  # Flask 애플리케이션 디렉토리 마운트
    command: ["/bin/sh", "-c", "/usr/sbin/sshd && python3 /app/blockAPI.py"]  # SSH 서버 및 Flask 애플리케이션 실행 명령어
    environment:
      - FLASK_ENV=development
