version: '3.8'

networks:
  app-tier:
    driver: bridge
services:
  node1:
    container_name: node1
    networks:
        - app-tier
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/sh", "-c", "/usr/sbin/sshd && sudo python3 /app/blockAPI.py"]  # SSH 서버 및 Flask 애플리케이션 실행 명령어
    environment:
      - FLASK_ENV=development